### ISSUE TITLE
Multiple instances

### ISSUE THREAD

**Issue by MatthewBregg** [JohnReedLOL/Nineteen_Characters#104]
When attemping to launch several instances, the following exception occurs

java.net.BindException: Address already in use
    at java.net.PlainDatagramSocketImpl.bind0(Native Method)
    at java.net.AbstractPlainDatagramSocketImpl.bind(AbstractPlainDatagramSocketImpl.java:96)
    at java.net.DatagramSocket.bind(DatagramSocket.java:396)
    at java.net.DatagramSocket.<init>(DatagramSocket.java:251)
    at java.net.DatagramSocket.<init>(DatagramSocket.java:304)
    at java.net.DatagramSocket.<init>(DatagramSocket.java:276)
    at src.model.map.Map$GetMapInputFromUsers.<init>(Map.java:179)
    at src.model.map.Map$GetMapInputFromUsers.<init>(Map.java:174)
    at src.model.map.Map.<init>(Map.java:154)
    at src.RunGame.initialize(RunGame.java:79)
    at src.RunGame.startNewGame(RunGame.java:57)
    at src.RunGame.main(RunGame.java:53)

**Comment by JohnReedLOL** [comment]
What's happening is that every instance is trying to use the same port number to connect with the internet.  If you want to fix this, you can type in /set-ip no-internet and it won't use the internet.

**Comment by JohnReedLOL** [comment]
Sorry, only one instance can use one port number at a time. I would have to make each instance use a separate port number and I would rather just stick to the server accepting commands on port 14456 [That way we know - hey - our application uses port 14456]. If I use UDP, I don't think it'll bind to any port.

**Comment by MatthewBregg** [comment]
I'd prefer if at least it at least send a detailed error message rather than just tossing an exception.
Maybe have it go to local mode if port is already bound?

**Comment by MatthewBregg** [comment]
Closed WONTFIX
