### ISSUE TITLE
Nullpointer exception during attacking

### ISSUE THREAD

**Issue by MatthewBregg** [JohnReedLOL/Nineteen_Characters#115]
Exception in thread "Thread-2" java.lang.NullPointerException
    at src.model.constructs.Entity.commitSuicide(Entity.java:573)
    at src.model.constructs.Entity.checkHealthAndCommitSuicideIfDead(Entity.java:561)
    at src.model.constructs.Entity.receiveAttack(Entity.java:985)
    at src.model.constructs.Avatar.receiveAttack(Avatar.java:84)
    at src.model.MapEntity_Relation.sendAttackToRelativePosition(MapEntity_Relation.java:352)
    at src.model.MapEntity_Relation.sendAttackInFacingDirection(MapEntity_Relation.java:409)
    at src.model.constructs.Entity.acceptKeyCommand(Entity.java:526)
    at src.model.Map.sendCommandToMapWithOptionalText(Map.java:426)
    at src.io.controller.GameController.sendCommandToMapWithText(GameController.java:214)
    at src.io.controller.GameController.access$0(GameController.java:192)
    at src.io.controller.GameController$ChatBoxMiniController.sendTextCommandAndUpdate(GameController.java:61)
    at src.io.controller.GameController$ChatBoxMiniController.processQueue(GameController.java:136)
    at src.io.controller.GameController.process(GameController.java:317)
    at src.io.controller.Controller.sleepLoop(Controller.java:74)
    at src.io.controller.GameController.run(GameController.java:168)
    at java.lang.Thread.run(Thread.java:745)

**Comment by reidholsen** [comment]
fixed? (probably)
