### ISSUE TITLE
Keep crashing, getting this error.

### ISSUE THREAD

**Issue by reidholsen** [JohnReedLOL/Nineteen_Characters#118]
Exception in thread "MapInternet" java.util.ConcurrentModificationException
    at java.util.LinkedHashMap$LinkedHashIterator.nextEntry(LinkedHashMap.java:394)
    at java.util.LinkedHashMap$EntryIterator.next(LinkedHashMap.java:413)
    at java.util.LinkedHashMap$EntryIterator.next(LinkedHashMap.java:412)
    at src.model.Map.makeTakeTurns(Map.java:356)
    at src.Not_part_of_iteration_2_requirements.MapInternet.getInputForMap(MapInternet.java:134)
    at src.Not_part_of_iteration_2_requirements.MapInternet.run(MapInternet.java:70)

**Comment by MatthewBregg** [comment]
Fixed
